google:
  auth_endpoint: https://accounts.google.com/o/oauth2/auth
  auth_http_method: POST
  auth_params_mode: query-string
  token_endpoint: https://accounts.google.com/o/oauth2/token
  token_http_method: POST
  token_params_mode: both
  redirect_uri: http://localhost:8080
  auth_scope: https://mail.google.com/
  client_id: XXXXXXXXXXXXXXXXXXXXXXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXX

microsoft:
  auth_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://login.microsoftonline.com/common/oauth2/v2.0/token
  token_http_method: GET
  token_params_mode: query-string
  redirect_uri: http://localhost:8080
  auth_scope: https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send offline_access
  client_id: XXXXXXXXXXXXXXXXXXXXXXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXX

yahoo:
  auth_endpoint: https://api.login.yahoo.com/oauth2/request_auth
  auth_http_method: GET
  auth_params_mode: query-string
  token_endpoint: https://api.login.yahoo.com/oauth2/get_token
  token_http_method: POST
  token_params_mode: both
  redirect_uri: http://localhost:8080
  auth_scope: mail-w
  client_id: XXXXXXXXXXXXXXXXXXXXXXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXX
