name: AUR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release on AUR

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Deploy to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.4.1
        with:
          pkgname: mailctl-bin
          pkgbuild: aur/PKGBUILD
          assets: |
            aur/.INSTALL
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: release mailctl-bin ${{ env.package_version }}

